apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zitadel-secret
  namespace: zitadel
spec:
  encryptedData:
    config-yaml: AgAzRkLboBi7D/bp1udkC4DH8zz4aB/VFmpTPMphdLFj/aJkGVbD0FT17fE2tRItPSHZ2c/ycwd5HH2p0oyUYSta6eddWWHKXAvWLEjGxsV0Gk21WCbhnTamMg0kiww7XN5B+dhPZIOsLiB/CLr8PqrKmz1qO4UE7MSEMLBvbuPvhWLbUNrNWC0nKMdMnjUoVVe9psXSBYckgXPSOQT34Ok/Gr+//FbW5ZB+BdZ93hSMynFIFDjmMIYnFgXJ78kvaaYJdD1v1WYi35JPEpKDDCSMIyvXgLIK+RJQvLpfBAv/SNGmZYWaqoMmlitlb8aoAJjgCqoUIyMcKklQPF5413vKJDRsxzdVK0DPt0T4QahFyIJnIQ3ib/+Nkg5V+6omBBq8De4ThcAm+FFXtaULNWeQPYKND6+rdc2nKqJwmf42Cz4+gX5m051c9tK5ThV0OPgESSomAC9tulWeMDO94MurmT/DMs6/Vluapk05Wez3qsjTIaSwheIMH/v6v2mMrTmCWJTYygoRimOI+P5/wXFomhgW2fVyU3IjK0MISTniiR3fzjjQmYLXwYTlNIGXGeh0zdcNVdg6Jc8JP0XUCaYdd2lvFiJEJGhE8tU5Z6TKpKLcbbgjmUV1A005rR/pvNDRYU1IqGj9ICaqqDfG+LkMPehSMFa7l1exxbx1BjfoBFdMxQm5IL1eUC/pr3aiO1H2og0uxxnzdpglE7Bs4uV+8jHYaKQAWOlHJpujIvxgYco80POcPR9dBLfml5t1l4u73tCWVNSsbOenujPSwh0Pgn2Ge9hwXSi+W+s8HjIiKmGuL7OvAOIiEbASrmsVLABWm2al1qB/wVoXONJ10Ep3JkNU36fpR6OaoZss6ee/3nYQoJ3IHpUTc7rPiRKbZjVLO588HV714+++5/XaAwGQ2EoBtj2xoY4/JGpk8P2F0UunaN7zmM/cbAASDC+UnV8qYCNAX1E3qEuoTKub/BvMoEIBMbVf/OGO3oY285uSJhD58qujUz2hd1w0c85R/kVD8QXYH9V7RwjdhAftE3YgCjWZBh/XlvOofrY65guelHkwCLvG8frXESWv6/6LPJGfvWZ+BhQXmWIMJ+I4kzP0kocm5QoVTZlaRnDhGgQBcMd1aRvQC4Oe8RvZi0I2uTDV/DwM
  template:
    metadata:
      creationTimestamp: null
      name: zitadel-secret
      namespace: zitadel
    type: Opaque

