apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zitadel-secret
  namespace: zitadel
spec:
  encryptedData:
    config-yaml: AgCK48OuYrrbLPV5a4NGDmlgHsfAE9c5lg19v+RohL+G2ewfBcJ7gGZuruK/OkontLBT2Bb722itJdu4X7MsHGcENXs2c/qIGy4/4guR+Naxdp5b4ogr2vws9Hk/r0StT9/FkR+kv5PuQ1fSw0i6ssuk5zG/T1zQDjqOYNdIUQ/t4PQJ0gZxdmASjQVpKL21dPuVxKCmyicU8LcQQjoYp7ia0e0eTvRSOgie4e8htKhxmxbSTtvmPMVu9Fo02gVtPhlVP0DA34RaDKMOJqztbdiguXdClcVN4SL9ZfzKkB7rhc88X3oS8cIZxoN5uaZe48tqvIfNG95PPgKdQ6Qw8qSZLeMfx9QxYzlZEFxbhRFPK9zDHRogdb7jB25tmQjmePd5sl8oadCSRQSuLAAvVdRW1p+iG0updFFK5wJVXCG1QNw8tSm1jK0yCxMxLeGDMmNqPAQcVjaWM8Yy11vQ94rmsmqiJfVDLdyqE35QDpLH+YJeusifhz6zeDr6w57qoYLno5ajj9GRsRVMOV4Vs//K5DFag2Iu3z9SoGMdj3VUWEdDdllw+/eYcJkJwM9jyQSh27Cgqa1fJ70X/6rqpysado7NIhdaOzBQWeIb36036NC2IBB7ZXNcH9oHGeEBPNpaMqko76LIoHSvZqdypmCAI/tpcK3XuJWZg7tp0VESJGIkusDt8+igSb2izgFiJ/uG9tl+Mlj0/rv1RdYPNdc0G4TP3r8gOpaAp9tDozvui24noM0OgH2sUkvvB0vRVHgr4awa0CzYv75tc9k9CoXQAzzcKc4N0AXyn4yGHTPY3uq6BZTl2yqbnQVifRAI5g0oYKwp8z81ox3DSuu1uQh3HOu+I8ojMLSBL76zJ0PpBcRchevIsaoS7qcJ3Fk/H5WCjJWz4v7hwPXDtNAUVem4kbwWk9EsjHxPRfQk0W/WGAAjnBMcUBLPuR7+r7XsXL5Feex3g+bx7bvRoWgiyGljzv82RFywDJRoQtqhq+mXMoZGw9wDSTyoSmZp4OAnAj4v23/ivPeOvu3zv7Lxee9cl8RgQtfbrTuJhJ9LtxwqqvAyXgzn43EykW+mnjrVEgkrTYKfOwWkG7cvuIMx6dfWSBvFS34g
  template:
    metadata:
      creationTimestamp: null
      name: zitadel-secret
      namespace: zitadel
    type: Opaque

