apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    adminPasswordKey: AgBRN2BmxQKR8GminEpjjVJCLPhzIQUCH4UncqGkgts1t0ITmFf8uAXkFG41kuqqyvefAQym2kCRhyiCpIxRepyHwW/kooYZwN46Ia3oXJ/P2oy6n1BCeJhh6CUZ8tMgAuf0LDpX+nKEen58+/2oIqovARpS43PoquV660e51FPIZcdZzfcW0hG+JlAiOYGLgGaNByQCrnNoatXoyYiAcQiKZeHpbH8NkT1jWAiCcDrxxTLdNFPEVn/g17/WZgdGFQhKsJRZeETrblnxXjl1bRQSrIPSPdjzEl6UlcxSIto25GtXlAPO2poqeBrntrIIk43MbIw3TrGuXQhFKgd/a/toiLG0ejk5SuENtSZAzeVs+RUkTWDVglVRvNqtbB7Asf9WwI9ziVK+iyawGq2dYldSbADC04rBd8dD5BU6FJ9aC/OFf8gzpCN7jsm5mntnPX3SpmN5cJ+xmh0h4dmwuFlYKt+LV7/ddV88TK/Nq2augXBz0znAyHFWiUNkyQscANBoiCvsDeTBZ8Hg6s9VQItUYPK/Qr4qpGuEl3KjPUY2LIR3lVWrlnbmWvAAbBCs0+DXyaTExZLqgL/XPx3CZixRYj4gS9ypMyG6m8OGN/cgjqYpowohJWbQ4Kk+El+d4s6qyY6/SIKm/DuPQOELJvu/SBu+6/5WppyxrlxCecCA9qUtIsAGVajm9DxI9wW61z7JgCeTKg==
    userPasswordKey: AgAHcrSGj4Z9bBJCJgPF4qofjBM0S1NCNDM9VHcWJMqiDlkMRzBM7UHAMOcjzPMrw2ELrPc/JB9fxPWPO6pWXPnZRftzxEYLAo4LZS5htTqpD0+ZI1UjysL4+T+1zqvtg/vRVeJh7hHOeeJgLLqssX6kKP9jvT6HRuFk2jAfSlhX129DzeoDwKRDO3iBMPx8QY7ZmGVkYFDsbm3YWChva1ZB5xrDhHij6dnlGAxGP+zi/t13r15e8ISX7kyRrqqMcd2OVz3s2lkUfwerc3vCSsmOMC7CbDQXaneUnqkkIifbVVImN4r7miJV9AEhpu9Kl0FpdvfYxxbtBw6HJKcOutg6kdHJDOMajM0+ixcLNJjfxl98aIt/T8gdytgxLIJhJxGn/cBx8pYlInP0WVHONtJVxDqGXD5u3QAYw63Jxu7Eqg83xTMyMuabT5HLN2ftFaq/BdqYdoSarQxPKLOD2OUao/SYWQSmfhjWHYiP0fJ74aJqaZ9f5REg7aohITEJj9JvArDxuG43DX8JKWxBTsLqmRwyan9cxE61Qo2rfiYxzz30d0OJLoyFO75jXDmURA0cifab3T354ufHKVjO0IEqgIYLr+dGNlPGqKD4SuBUTWR+znMx/rd+srFO17RK+P2hY6JFuMwW09kNFZM0uE4OTRuP2dCDWuwdkqyV1P6DhrljWtTW8TtwsYUWKIht1Uvh6QugO0uT
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgres
    type: Opaque

