apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgresql
spec:
  encryptedData:
    adminPasswordKey: AgBninQtUXEU7MqFWNcFzDxY6W1o28p8p9WDveXPHoyG8V4qrhX5hML5DBIHXYZb0CefIwl5r2lsWtRBZcFLD31LKlNXC7QK88OeExLdv6OgQzNzS2PtD+Al0WwrGSaT/FHDS+uuEMQamj9Uvjr/ArQZOytgi8VSIKl2aTUawYKvz7kIX+1ak8IS3Qmf2mUx3eT4ECd5PnGy5X2IT8oIbDBi1RnBjJ1CGEgPmWQMiR4j0f9Fs33JYR2RM9TggwAgAJvL2CpkSEKDZjNAL+fQ4hs93HAvXF0tekhemFO/VczrwA4jfdnMP1x6ycPSX11pfbThNJm6/Aszv1kSApYC55V25l8/co3xxzq3isf6mlZE3lxKHGL29H3h9jxxAKoWbDjFJod386eLwuuJgXDRoPoe89R4HiCWQ2lRr3BVBQpx1BUuuR2dxOQ6SkA48yo9tiZZZzgmf5NuPUuf0zQt68pCc5YnV1oauG3ZrEY72oB+D6t5xKxs5f3VFT91Kgx2+2D1fBYxB+/ad6kwVcp8JWytgS/ivJqK3yd/ForL0BBQrE4HSjqmKlOOSoA63HzyzSWLVAQ3/Rxn6ibVcNDrxmbjKaG6O8pPvhUw2LekPToLkTGJEX9f31ssdaQeqpQJwmhKOp2BuDf3RWo9gwgwPusQ7e9s+o5Dj8vUKOAaUPmSiLPlGkow7uM7I1EECD1tN7Vgpo+7aA==
    userPasswordKey: AgBzJCghHVnNS20mI7CuppJ1rMG8xCwYTeTWbm+9ZzPlbLfGePE3X7Sxsxl9HYSoFcY54gOCdxgf1gobo4C0fPNPNK7Smf6pMawHrL9dW6pnPptXJemanwv81kfs9qfKFA5UX6WPKa+802iRqGgDi5GkGpxeNCCXzlDBABtxLeTyuSkpvWcxvUlOYLnHwCU7Dv/cSFWgBmyEhlPICNyTzL1k3JxcIbUaKQBbiSg/Q9mKLWjxgnVJtwDfBfPDDlo0/n+Va4T7d8VwnX3a2ExtFg688D1j7x91d2zcje6U6IOKaI02QUI+DorVkoIhEGzUAqlgl09tS4OSCUfaKmn2D/BHY191XQMxXTgPowX/cXo+AcuzpIcfc8gKrAR+ge+C93CeHARcPwrxNIbvgW1SY2ilYYvPK7GyLahIzAXLHriZAc2lYPm+3+Xx2Dlyfdx3wG36fRHpR02Zf41e5b4PNof/6ow6G31CaIS8vaYDb1pnmMZlpbWCtilMWq9ELFkZzDylvw24sqZ40RWOrVlNsUTwp/01gD3qsnAGRGUF2YN4Z6Q2I8LZE3mlNEMAjY9qoTOu/deccLZ77NQnfBTZURQuvtXaqTWuXbSr7lCUNIGyowUhIPZH3WkCUfjIhs2qlbYwNL7C8jkd1tzIWjSmTZr3Ztsara9F1xDK3AtpLVYdxFofAinTMDVDQcZs5cSOO3XchofnLFhH
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgresql
    type: Opaque

