---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgAi/NLYWvrbEzPaVPhQbZw1S3Fueo3wR4cWT95+/m3DvGzI2JCjCArWQUrMJRMgWWrNJYylF4pAAul3LJSWblIhV5S4j+DVB7329dvXOmJ57xMM2+oeBpEtklW+/7Gp17y8YJpUuXFFRwGOFVfOaKiNGxUfAF++5zycXnnHuWyTJprLkdg5JSpSw9SUaMPFLoG1lLYgoUxS5FwoUHaxfqP6hGmsZGQGtgmBmV6kN5W+hA0FAZ+NNobfyFKTnVWBaemhPFIIkK4Sc3+SSnMSFQiS1EAz69uxGlzww5du+wLUmqXTr48laktFmWCuIf4zGSSdYiKhiteaCWOice92VmeqxbVjAoyd3es7ll74q2OVhfcog/qJ+6BbKDJQHHSaOz1kKMsvGR1Rl9cM4y6ov2Cacr0r6Mfko4tVr2wnr8A9kN6yV2VucBuY/vHGeN4rYgOC7nmuw6ioKOFghU6C5nsk/w2oFaPzf6XiqMvVVdnQbzwdyynVR8RBVB6D4PgPIGJnh6Bei2XkdlJFRIJj7bPWDYlyV6RkaTyNzzUgKbx/0k5HjMhCLUVJWjHLrAvo8De+mIVIxEpZj9CUkyqxhf6I/ch2WjxgHJS4XH7g+p5UiIp37fV4KCw/7u4cKSehljEAlutdSw0BpskPPLc4f7u3bA6zjKE1Kt3UEllL9A7EF3X0en0oXvL9CKvzmSKn0qpajW0JMulz6u8a9eMQwSIIIzSlddnyCRU0RWOjBaISHPgoeVu6fVvc8OiR7c+lOc+OsFkJYZdbsIqQjhg9jVd2XGvUMu2qLlSPC7M3ZiwLf+5oK0Bs7AoFF/X4kDCtpGpwypTgI0YFw9z+gvGPowBfLFQ5FPc=
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
