postgresql:
  global:
    storageClass: "local-path"
    postgresql:
      auth:
        username: "zitadel"
        database: "zitadel"
        existingSecret: postgres-secret
        secretKeys:
          adminPasswordKey: adminPasswordKey
          userPasswordKey: userPasswordKey
  networkPolicy:
    enabled: true