---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    backup: AgBM+g4Upcav5IRD1mHqugJRPk6Y9+8Xb6Fd4aqHkaf3FSiM0/aI+9a/cimV+bPnQCuHt8v26UvsK5q413bnaQ+hIgKPlH0jmU0I2aq09Cqm6tPXGDvLX6oGwOT+nANpLbgeLIKVGFjxZtcXUgTRKS66nLRvFov/FY2iuX0Xa/Qa+kN6aKxD97DZAGXKW3wi7rdmvLtInv6nDGQYVBoDr99g3WXZ2lLiavVPcoEWX0aqnkvOIUfof+HuPXL9SFJ/npsD2lLiDpJscr0Z9AWzj2xTPRCe4WhyHvhpOf+WZ25CCdauyXMEBtIJcjZtYvkJ0abSeOVGRGP9BaKZ501WrQhT1/BK51Szi0R67dMGzAw+E/cuz6tIZY8YX/p1jKTKpkCdV3BBY+Q6b2CjUiU/uqH1xZHH4DCmxia+qHOEI8se38ODLPzywypE1l4PXILiDbptS5eSLTVmWFq9DvzrU8pPdqNzu4w0Na8nulgITb5u65Us6Wt3oLdxLNwFnnN6wKK0WGv26VDiv6rStqB6LK/J/soC0pfhgrdEp7hu9EXdVzNLZ8pJcUSzFlqIc+ghjEq0HGZrVW4U+IHvoUAbTfx5o/fVrGkVDPo4hkVptz/LgzNXjzhzHvTSoQ9HHcTB7266DoMANht3rtTq31SpDdNYPiUZ6OvscGGy/OMu1yX2cF3p/vELcTOD3Fcd/9Hu9O0o0iXICE77YERtDmMqUyMmr0aFucwR9o7yRoa/4EjixMA5oBAZr4Lvp4YJzxPy0yOfgIaQG0pqTM23VmeU63XfNmR1ClD0K8Y4X3GWSJDVytF8FgZ6ysP+wCuyvZ319tK+MluEWtd02uW7aclOoLUlMQSZN4g=
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
