---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgAbzIyF1pQgrgnDa9ShNcR1C1luWI09Fr0hqwW3ZWTsa+h/69mIYwhCtmoqQKJKoJxr5+1k8ZI1TEtHRc0TRfiqeajkz23HivRsl9g7XK51L4bHGEMl9E9qvsOzf6ZOJpKIV1HtFxekyTstFQqmLQXYgs3ugMvPLRy0OkowHcEdWhW/4HfbV7Ck7p+nZzmUUBXtb06T1cPxD7OIxK4yFYuvFmZddiumc0d6RJPmF8GgcyKbebv9/zdJpBTMBM7om5dti28OLojFuWtQ7xbys80LOS0iMRsJ5V6/oC8eBtlQx4/I60VfnTHp11sh94jD1Ahew6+sSaghdL/L5gAdIvvLOHxTgDB7dK+Jq45Pqrsb3fVHnpv8zjtgivq0mA+y1R4XXGZTfioA7/3YpTsjYzU2s+nhYVM6fsV3NoUBRUgK/F3g6FkBOsb6LxgMtNkS7v1yqjeozmWamg7T9qQXcPAu0hLGVTcShaKKilHzpXogHrHjQvvm7Zxy4bQNoLxLxoEuNv1i9OSFDOQhbLv6z53nzK+Rkl1rcd736aRLopYkGNxIq0IwtVYGZaYhDYoXdNuAA0vtEcL8Ydz/FgmzkWpc6xq0jt5bhEHq/Xg+15vDYa6XZqokuakBSUcP7+bg7XtNMyv1glJscjldw2svwdubhT5RkkbgNC7M8JGMYZ1gXvW/aB1aGBqrIRhXpnY2rNmwckefaxileRtWuUctQY9IALG13h6rJUX/biJhYRYmPgfwsbcgvqn456ciSKgKIFN7mjq5FCj2bZoIH1guLgVvDr5TyfQKQqi1w92XB3r2CA2zhy4ME3YvPLByxjPTOytljgv6ntp7mSjTt4fqCtgg
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
