---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgAuTROay/q8dWtE95wWGjS+14l1RAtZ2XBZYH14prJ3zK1NJ5NeuBLoWF0b3vuPzEgoCdHeSGI73vsuvWBVY/+iZyl/1rjqIBZrOpVFbX3PkEF5mVorfd7LcVdYMla4DOBv5I/fPmvZ9iSUCSWfQxee9wPK19oGV2sHDPPNt98o6giyCH6rw0xPAno0i92Npyvl6bYYBDqdYwbjxs+pQHNMtxUOM5HK/XoXLzWN9DH+AblWo9xRMG7PknJ40AnBq29/tPxWY321dyV8Lnhh0bAZr8tFFg5AmbkOxdgcAakptXOjZGH8Ec4N1t3nHKs2FABj5nwEJLJBmg0uAIFid0JSeXdmLhTbVRx24m1nEbWRwubful66thjwgZgk9cGuqqyPsxgkDNmQeCdpLaFkZ2SygNqJXyKJPOXdevDQuInBaIQtRpP/g9Y7M43XDRMogGw4ieaqOiCp8qEg2f2u0zF3VjEz6ABcHqygJlQNaJ2zK1sfX4pIkf3T+vXX8vkPQRhStwe7/nxHbu8Z3kOv8lOBEd2IqDMH9iL9xO5lnT1CdT+kdILsebqTMWy8SbeEFyuZHWQg5SP80TGe9b0l68oyUvYf1w2MNVUTzeF5ATnvoFpDs7YO037iZjz9MkGmMnrMU7lab4K5DYfBkfkJ0xW2Vx7U0hCp1pOk3CTwwQs3x893nb/0UbPGpMMDCZpwtdnaXJ0KRkuUigy5V/4gEe7hz7JP2BGm4qUA2APqMCo8UTAErbhZnY6Ri+ZVT5QX5/M48MvWvxdccTvegmhpedBTjoETE2+Sf4OtRPCYl4jA/5ef6HfZJ4apU4YFDMS61eMf3a63jhMK3WhvXPISGNUr2vWczsM=
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
