---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-secret
  namespace: velero
spec:
  encryptedData:
    backup: AgCx31Y0pFCA/jR73aDHI+ww7eF9PLgcapAuicb8nLxQ/18abNFFS8/ShQk0mGaRdqC1HhgdkrAhBXWn1O87nfh1U9li5+ysnmN5cI8I1rUjytpsju5CRwnPqNnV8TXz71OXbTbrEpDEM1yTKef+URmTGzT9tlPxQbAdgeqshQpgGcwp5Bsmkt+0PSHe/LsTeWIom5niQ5rLDOx0y2AFxLn7DVC7eS/gI2jRg2g/uwIxTT7syhTRdgvWroxdinhYK1o/e1pSXJJnP4b4Ij4XKDpIW90AAnqqgc517qIiGy+xQ7iHo0AJR4blIaCbhTbFFNx84C879kcPiqxAd2G71vqCsGf7QuxQi1IH9I4Flp713DtbzJYskra/T7dN6/m6uyAWi7Tpt4mqsw/zK27OsA6zoqOIi0aQHm9ZYZsjqQL8je9/i1ViQEgYHd+j1qhcNV7cebQMYnOEcj6cH/Wgo6nSq6G9W8GgX6ixCEKXFpwaaL2A3VTJQ7AHUgbNm9speZtuu/EwJfWcSpw0n0TyIb9XJEf8ErXXZGRHyneVIxUG9FepKzCq0gnis2qSp+AahzWcTKKQmRs9Y7eaA2G8hWjPWc3qPaYz6kwL5jtmN8ansSu8inkHGW6Vr/oLI89xBzQttSWD89zodAQN9ARrsyw8IC9mfV4AsDeSN7E5pDOLoE8IP5zJOvIoAAxo4bFkgQNPWlrI48a1z3o6AH6ERRJqIq4+dawmy4XMdgp/fWXO6PQcG5Ex6cOU4rv2XsKr9lDifgBUHE+tAgi4EL3+o4jTzknMGI0D0YkTDgaJnldMG1tDmrzy1R5KclZTqJD3vumY+6LlehK4ENqgVdGujIIh
  template:
    metadata:
      creationTimestamp: null
      name: velero-secret
      namespace: velero
    type: Opaque
